### ISSUE TITLE
which python script to run to convert wapo collection

### ISSUE THREAD

**Issue by yifannie** [grill-lab/trec-cast-tools#2]
Dear Sir/Madam,
I downloaded the WashingtonPost V2 collection from trec CAST website and the corresponding duplication list file. I found that there are 2 version of python preprocessing script, wapo_trecweb.py and wapo_deduped_trecweb.py. Which one should I run? I tried the wapo_trecweb.py first without duplication file, il prompted me that I must input a duplication file as argument. I did so a second time, it returned error on this line https://github.com/gla-ial/trec-cast-tools/blob/master/src/main/python/wapo_trecweb.py#L97 saying that write_to_file doesn't have sim_file parameter...
Should I use wapo_deduped_trecweb.py to preprocess wapo V2? But the wapo V2 website claims that it has already dealt with the duplication issue?

**Comment by vaibhav4595** [comment]
It seems like there is a small bug in wapo_trecweb.py. You can simply use wapo_deduped_trecweb.py in which this has been handled. Both the scripts are essentially the same. However, if you do wish to use wapo_trecweb.py, you can add sim_dict (`def write_to_file(fp, data, sim_dict)`) as the last parameter to the function write_to_file which should probably make things work.
